version: '3.8'

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx_net

  application01:
    image: claudiolibanez/helloworld:0.0.1.RELEASE
    container_name: application01
    # ports:
    #   - 3001:3000
    environment:
      - APPLICATION=Application01
    networks:
      - nginx_net

  application02:
    image: claudiolibanez/helloworld:0.0.1.RELEASE
    container_name: application02
    # ports:
    #   - 3002:3000
    environment:
      - APPLICATION=Application02
    networks:
      - nginx_net

  application03:
    image: claudiolibanez/helloworld:0.0.1.RELEASE
    container_name: application03
    # ports:
    #   - 3003:3000
    environment:
      - APPLICATION=Application03
    networks:
      - nginx_net

networks:
  nginx_net:
    driver: bridge
